version: "3.9"
services:
  agent:
    image: prefecthq/prefect:2.7.6-python3.11
    entrypoint: ["prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    depends_on:
      - orion

  orion:
    image: prefecthq/prefect:2.7.6-python3.11
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@db:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - db

  cli:
    image: prefecthq/prefect:2.7.6-python3.11
    command: python /root/flows/flow.py
    working_dir: /root/flows
    volumes:
      - ./flows:/root/flows
    environment:
      - PREFECT_API_URL=http://orion:4200/api

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    ports:
      - 5432:5432
