version: "3.9"
services:
  ### application
  orion:
    image: prefecthq/prefect:2.7.6-python3.11
    restart: always
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@db:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - db

  agent:
    image: prefecthq/prefect:2.7.6-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://orion:4200/api

  cli:
    image: prefecthq/prefect:2.7.6-python3.11
    command: python /root/flows/flow.py
    working_dir: /root/flows
    volumes:
      - ./flows:/root/flows
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    depends_on:
      - db

  ### backend
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    ports:
      - 9000:9000
      - 9001:9001
